create table pokemons (
    id int not null,
    ndex varchar(15), 
    species varchar(255),
    forme varchar(255),
    type1 varchar(15),
    type2 varchar(15),
    ability1 varchar(255),
    ability2 varchar(255),
    abilityH varchar(255),
    hp varchar(255),
    attack varchar(15),
    defense varchar(15),
    spattack varchar(15),
    spdefense varchar(15),
    speed varchar(15),
    total varchar(15),
    weight varchar(15),
    height varchar(15),
    dex1 varchar(15),
    dex2 varchar(15),
    class varchar(255),
    percentmale varchar(15),
    percentfemale varchar(15),
    preevolution varchar(15),
    egggroup1 varchar(255),
    egggroup2 varchar(255),
    primary key(id)
);