create table typechart (
    id serial not null,
    defensetype1 varchar(255), 
    defensetype2 varchar(255),
    normal varchar(255),
    fire varchar(10),
    water varchar(10),
    electric varchar(10),
    grass varchar(10),
    ice varchar(10),
    fighting varchar(10),
    poison varchar(10),
    ground varchar(10),
    flying varchar(10),
    psychic varchar(10),
    bug varchar(10),
    rock varchar(10),
    ghost varchar(10),
    dragon varchar(10),
    dark varchar(10),
    steel varchar(10),
    fairy varchar(10),
    primary key(id)
);